### ISSUE TITLE
Spoolman Reports Invalid HTTP Request

### ISSUE THREAD

**Issue by bepstein111** [mkevenaar/OctoPrint-Spoolman#30]
### The problem

I have a testing instance of spoolman setup via docker on the same PC I run two instances of octoprint on. I just re-installed debian from scratch and set up both instances using community octoprint_deploy.sh script. I installed a number of plugins including this one, and configured the URL for this plugin (btw, the example says HTTPS://(local-ip):7912, even though spoolman doesn't seem to have an option to serve HTTPS at all let alone on port 7912, at least not via docker).
Anyway, I entered in a few test rolls to spoolman, but am getting an error whenever Octoprint tried to make a request to spoolman (from the spoolman docker logs):

> WARNING:  Invalid HTTP request received.

Is it possible that this plugin only does HTTPS by default? If so, that seems kinda like an issue for anyone who doesn't want to set up ssl just for a local server.

### Version of OctoPrint-Spoolman

0.1.0

### Version of OctoPrint

1.9.3

### Operating system running OctoPrint

Debian 12 bookworm

### Printer model & used firmware incl. version

CR-10/Ender-3 both w/ Marlin 2

### Browser and version of browser, operating system running browser

Windows/Linux w/ Chrome

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20231029181346.zip](https://github.com/mkevenaar/OctoPrint-Spoolman/files/13199386/octoprint-systeminfo-20231029181346.zip)

**Comment by mkevenaar** [comment]
@bepstein111 The plugin hasn't been released yet. I am still working on the development. Please watch the repository for the first release.
