### ISSUE TITLE
Impossible to use plugin

### ISSUE THREAD

**Issue by platini76** [mkevenaar/OctoPrint-Spoolman#31]
### The problem

when I install plugin my octoprint goes in safe mode and save spinning.. no solution

### Version of OctoPrint-Spoolman

0.14

### Version of OctoPrint

1.9.3

### Operating system running OctoPrint

any

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by mkevenaar** [comment]
The plugin hasn't been released yet. Please wait for an official release before installing. You can watch this repository or wait until there is an announcement within OctoPrint
