### ISSUE TITLE
Does anything work yet? :-)

### ISSUE THREAD

**Issue by hcooper** [mkevenaar/OctoPrint-Spoolman#34]
Came to try out the plugin after setting up Spoolman. `Software odometer` is ticked on the README, but I don't see how this is implemented in the current code (e.g. calls to the Spoolman api).

Also the plugin currently break the octoprint UI, with the error:

```
Could not bind view model SettingsViewModel to target #settings_dialog : value@http://octoprint.ak/static/webassets/packed_libs.js?6bee1dee line 131 > Function:3:58
```

Just wanted to check I wasn't missing something. Might be able to find time to help get things running if that's helpful.

**Comment by Thormus** [comment]
hcooper I have the same experience as you with my octoprint ui breaking when trying to install.

**Comment by mkevenaar** [comment]
There is no release yet. You are not missing anything. 

I have some things on my device that are not pushed (yet)
