### ISSUE TITLE
After Installation cant never use save button in Octoprint.

### ISSUE THREAD

**Issue by Bersaker** [mkevenaar/OctoPrint-Spoolman#35]
### The problem

After I installed the plugin, I can no longer use the save button under Octoprint. the button is there. But the circle is turning. I can no longer save any other settings or operate any buttons such as system info or via octoprint. after I deactivated the plugin. everything works again.

### Version of OctoPrint-Spoolman

0.15.0

### Version of OctoPrint

1.9.3

### Operating system running OctoPrint

Octopi

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20240125175709.zip](https://github.com/mkevenaar/OctoPrint-Spoolman/files/14055740/octoprint-systeminfo-20240125175709.zip)

**Comment by mkevenaar** [comment]
There is no release yet and the plugin currently isn't working. You are trying a bleeding edge release.
