### ISSUE TITLE
Plugin causes endless spinning for Save Button in Octoprint settings dialog

### ISSUE THREAD

**Issue by fimmezwansch** [mkevenaar/OctoPrint-Spoolman#53]
### The problem

1. as described in title
2. The URL for the Spoolman Server cannot be configured, because there is no chance to save the settings
3. Plugin Uninstall recovers the normal behaviour of settings dialog

### Version of OctoPrint-Spoolman

current version behind "https://github.com/mkevenaar/OctoPrint-Spoolman/archive/main.zip"

### Version of OctoPrint

1.9.3

### Operating system running OctoPrint

ocotopi 0.18.0

### Browser and version of browser, operating system running browser

current Edge or Chrome

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20240408110616.zip](https://github.com/mkevenaar/OctoPrint-Spoolman/files/14903346/octoprint-systeminfo-20240408110616.zip)

**Comment by mkevenaar** [comment]
Please read the pinned message #36
